//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSimulator.Library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSimulator.Library.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet фрейм.
        /// </summary>
        internal static string EthernetFrame {
            get {
                return ResourceManager.GetString("EthernetFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;{0}&quot; проинициализировано значением, имеющем неверную длину.
        ///Длина переданных данных - {1}, хотя длина поля - {2}..
        /// </summary>
        internal static string IncorrectFieldLengthException {
            get {
                return ResourceManager.GetString("IncorrectFieldLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка &quot;{0}&quot; не является допустимой записью IP-адреса..
        /// </summary>
        internal static string IncorrectIPAddressException {
            get {
                return ResourceManager.GetString("IncorrectIPAddressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строка &quot;{0}&quot; не является допустимой записью MAC-адреса..
        /// </summary>
        internal static string IncorrectMACAddressException {
            get {
                return ResourceManager.GetString("IncorrectMACAddressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пакет &quot;{0}&quot; проинициализирован данными, имеющими неверную длину..
        /// </summary>
        internal static string IncorrectPacketLengthException {
            get {
                return ResourceManager.GetString("IncorrectPacketLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP адрес.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC адрес.
        /// </summary>
        internal static string MACAddress {
            get {
                return ResourceManager.GetString("MACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теггированный ethernet фрейм.
        /// </summary>
        internal static string TaggedEthernetFrame {
            get {
                return ResourceManager.GetString("TaggedEthernetFrame", resourceCulture);
            }
        }
    }
}
